name: smartlink
description: "SmartLinkViewer application for Neotelecom operators"
publish_to: 'none'
version: 0.4.2-dev.2


environment:
  sdk: ^3.8.0-265.0.dev


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  http: ^1.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  logger: ^2.6.1
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  package_info_plus: ^9.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - version.json
  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Medium.ttf


flutter_native_splash:
  color: "#030910"
  image: assets/banner.png

  web: true
  ios: false
  android: false


flutter_launcher_icons:
  image_path: "assets/favicon.png"

  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#030910"
    theme_color: "#030910"

  windows:
    generate: false

  macos:
    generate: false

  android: false
  ios: false